[package]
name = "rocket-multipart-form-data"
version = "0.7.2"
edition = "2018"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-multipart-form-data"
homepage = "https://magiclen.org/rocket-multipart-form-data"
keywords = ["rocket", "server", "web", "multipart", "form-data"]
categories = ["parser-implementations"]
description= "This crate provides a multipart parser for the Rocket framework."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/rocket-multipart-form-data"
branch = "master"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
mime = "0.3.12"
multipart = {version = "0.16.1", default-features = false, features = ["server"]}
chrono = "0.4.6"

[dev-dependencies]
rocket-include-static-resources = "0.8"
rocket-raw-response = "0.4"
